### ISSUE TITLE
Glitch Effect

### ISSUE THREAD

**Issue by Deuscx** [Deuscx/css-daily#2]
- [x] [Glitch Effect on Text / Images / SVG](https://css-tricks.com/glitch-effect-text-images-svg/)

- [x] [CSS 故障艺术](https://github.com/chokcoco/iCSS/issues/78)

故障效果：

## 纯CSS实现

原理： 

1. 通过伪元素 `::before`, `::after`创建文本复制

```html
<div class="glitch" data-text="GLITCH">GLITCH</div> 
```

```css
.glitch {
  position: relative;
}
.glitch::before,
.glitch::after {
  content: attr(data-text);
  position: absolute;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
}
```

2. 通过 `clip-path` 属性对文本进行分割

```css
.glitch::before {
  /* ... anything needed to make it identical */
	clip-path: inset(40% 0 60% 0)
  /* variation */
  left: 2px;
  text-shadow: -1px 0 red;
  
  /* important: opaque background masks the original */
  background: black;
}
.glitch::after {
  /* ... anything needed to make it identical */

  /* variation */
  left: -2px;
  text-shadow: -1px 0 blue;
  
  /* important: opaque background masks the original */
  background: black;
}
```

![](https://gitee.com/deuscx/tuci/raw/master/img/clipped-layers.png)

3. 之后只需要通过动画来改变`clip-path`这些来实现不停改变的效果

> 使用元素的伪元素复制两份图片副本，再使用 clip-path 对图片进行裁剪并且添加位移、变形、滤镜等等。
>
> 诸如： transform中 `scale`，`skew`， `translate`等
>
> filter中 `saturate` ,`hue-rotate`  `grayscale` 等

```scss
@keyframes noise-anim {
  $steps: 20;
  @for $i from 0 through $steps {
    #{percentage($i*(1/$steps))} {
      $top: random(100);
      $bottom: random(101 - $top);
      clip-path: inset(percentage($top/100) 0 percentage($bottom/100) 0);
    }
  }
}
```

通过scss的mixin生成故障效果：

```scss
@mixin textGlitch($name, $intensity, $textColor, $background, $highlightColor1, $highlightColor2, $width, $height) {
  
  color: $textColor;
  position: relative;
  $steps: $intensity;
  
  // Ensure the @keyframes are generated at the root level
  @at-root {
    // We need two different ones
    @for $i from 1 through 2 {
      @keyframes #{$name}-anim-#{$i} {
        @for $i from 0 through $steps {
          $top: random(100);
          $bottom: random(101 - $top);
          #{percentage($i*(1/$steps))} {
              clip-path: inset(percentage($top/100) 0 percentage($bottom/100) 0);
          }
        }
      }
    }
  }
  &::before,
  &::after {
    content: attr(data-text);
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    background: $background;
  }
  &::after {
    left: 2px;
    text-shadow: -1px 0 $highlightColor1;
    animation: #{$name}-anim-1 2s infinite linear alternate-reverse;
  }
  &::before {
    left: -2px;
    text-shadow: 2px 0 $highlightColor2; 
    animation: #{$name}-anim-2 3s infinite linear alternate-reverse;
  }
}
```

[Codepen Demo](https://codepen.io/deuscx/pen/ZEBGJoY)
