### ISSUE TITLE
边框

### ISSUE THREAD

**Issue by Deuscx** [Deuscx/css-daily#4]
# 边框

- [半透明边框](#半透明边框)
- [动画边框](#动画边框)
  - [1.border-image+conic-gradient](#1.border-image+conic-gradient)
  - [2.background+filter+clip-path](#2.background+filter+clip-path)
- [图像边框](#图像边框)
  - [信封](#信封)
  - [蚂蚁行军](#蚂蚁行军)

推荐阅读：

- [x] [CSS3 border-image详解、应用及jQuery插件](https://www.zhangxinxu.com/wordpress/2010/01/css3-border-image/)
- [x] [CSS 奇思妙想边框动画](https://github.com/chokcoco/iCSS/issues/92)

## 半透明边框

> tip:
>
> - 通过`background-clip`,默认为`border-box` 。即若背景不透明，背景会覆盖border。因而设置为`padding-box` 这样浏览器就会用内边距的外沿来把背景裁切掉。
> - hsla 透明通道

![image-20210210170210587](https://gitee.com/deuscx/tuci/raw/master/img/image-20210210170210587.png)

```css
	border: 10px solid hsla(0,0%,100%,.5);
	background: white;
	background-clip: padding-box;
```

[codepen demo](https://codepen.io/deuscx/pen/ZEBpXpq)

## 动画边框

关键点： border-image ：`/* source | slice | width | outset | repeat */`

```css
border-image: url("/images/border.png") 27 23 / 50px 30px / 1rem round space;
```

- slice表示如何切割将image分为9宫格
- repeat表示如何调节来适应尺寸。可选值 `round`（平铺），`repeat`（重复），`stretch`（拉伸）

### 1.border-image+conic-gradient

可以通过改变 conic-gradient 的起始角度

> 由于目前自定义变量不支持 deg，则需要使用`@property` 来自定义属性

```css
.animate{
  	--angle: 0;
    width: 300px;
    height: 300px;
    border: 30px solid;
  
    border-image: conic-gradient(from var(--angle), red, yellow, lime, aqua, blue, magenta, red) 1;
    animation: 10s rotate linear infinite;
}

@keyframes rotate {
    to {
      --angle: 360deg;
    }
  }

body{
    display: grid;
    place-items: center;
}

@property --angle {
  syntax: '<angle>';
  initial-value: 0deg;
  inherits: false;
}
```

[animate border codepen demo](https://codepen.io/deuscx/pen/XWNjeZw)

### 2.background+filter+clip-path

使用

```css
.border-image-clip-path {
    position: relative;
    width: 200px;
    height: 100px;
    border: 10px solid;
    border-image: linear-gradient(45deg, gold, deeppink) 1;
    clip-path: inset(0 round 10px);
    filter: hue-rotate(360deg);
}
```

其中：

-  `clip-path: inset(0px round 10px);` 用于构建一个父容器大小（完全贴合，垂直水平居中于父容器）且 `border-radius: 10px` 的容器，将这个元素之外的所有东西裁剪掉（即不可见）
-  `filter: hue-rotate()` 用于改变边框颜色

> 注意：这种方法实现的动画边框 由于`filter: hue-rotate()`的缘故，会造成内部元素的背景颜色也会跟着发生变化

[codepen demo](https://codepen.io/deuscx/pen/yLVazEG)

## 图像边框

使用**图片背景+纯白的实色背景**。为了让下层的图片背景透过边框区域显示出来，我们需要给两层背景指定不同
的`background-clip` 值。

### 信封

![信封式背景](https://gitee.com/deuscx/tuci/raw/master/img/image-20210211103210863.png)

```css
 background: linear-gradient(white, white) padding-box,
 repeating-linear-gradient(
        -45deg,
        red 0,
        red 12.5%,
        transparent 0,
        transparent 25%,
        #58a 0,
        #58a 37.5%,
        transparent 0,
        transparent 50%
      )
      0 / 6em 6em;
```

这里background通过一个纯白背景，另一个是条纹背景一起构成。

```
background: <bg-image> || <bg-position> [ / <bg-size> ]? || <bg-origin>
```

[codepen demo](https://codepen.io/deuscx/pen/gOLLYKW)

### 蚂蚁行军

通过改变`background-position` 可以实现动画的效果

![ant_walk](https://gitee.com/deuscx/tuci/raw/master/img/ant_walk.gif)

```css
@keyframes ants { to { background-position: 100% 100% } }

div{
  background: linear-gradient(white, white) padding-box,
    repeating-linear-gradient(-45deg, black 0, black 25%, transparent 0, transparent 50%) 0 / 1em 1em;
  animation: ants 12s linear infinite;
}

```

[codepen demo](https://codepen.io/deuscx/pen/JjbbPgY)
